DirectoryPath: "public"
EnforceHTTPS: true
CheckDoctype: yes
CheckExternal: false
IgnoreAltMissing: true
IgnoreAltEmpty: false
IgnoreEmptyHref: true
IgnoreDirectoryMissingTrailingSlash: false
IgnoreURLs:
- "^/docker-hub/api/latest/.*$"
- "^/engine/api/v.+/#.*$"
- "^/glossary/.*$"
IgnoreDirs:
- "engine/api"
- "registry/configuration"
- "compose/compose-file" # temporarily ignore until upstream is fixed
CacheExpires: "6h"
