services:
  server:
    build:
      context: .
      target: dev
    ports:
      - "30303"
    entrypoint: ["hugo", "server", "--bind", "127.0.0.1"]
    develop:
      watch:
        - action: sync
          path: .
          target: /srcqq
          ignore:
            - node_modules/
